# Generated by Django 3.2.8 on 2021-10-22 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='employee',
            new_name='name',
        ),
    ]
